//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by READ Test.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_READTEST_DIALOG             102
#define IDD_PROCESS_SETUP_DIALOG        103
#define IDD_READ_DEFINE_AVERAGING_DIALOG 104
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     137
#define IDD_GENERALSUMMARY              138
#define IDD_SAMPLEINFORMATION           139
#define IDD_TESTSEQUENCE                140
#define IDD_DEVICEPOSITIONS             141
#define IDB_BITMAP2                     143
#define IDD_EXPERIMENTNAME              146
#define IDD_READSCANNERLIGHTCALIBRATION_DIALOG 147
#define IDD_LIGHTMETERSCALINGCALCULATOR_DIALOG 148
#define IDD_READPROBECALIBRATION_DIALOG 149
#define IDD_MOTORSPEED                  150
#define IDD_PROGRESS                    151
#define IDD_PIDC                        153
#define IDD_MODIFIED_LIGHTMETERSCALINGCALCULATOR 154
#define IDD_JAZPATH                     155
#define IDD_CHARGEINCREMENT             157
#define IDD_MISCSETTINGS                158
#define IDD_DIALOG1                     159
#define ID_AO_DEVICE                    1000
#define ID_DCV                          1000
#define IDC_S1VDDP_B                    1000
#define ID_WAIT                         1001
#define IDC_S1VDDP_M                    1001
#define ID_DA                           1002
#define IDC_S1VEXP_B                    1002
#define ID_RUN                          1003
#define ID_PAO                          1003
#define IDC_S1VEXP_M                    1003
#define ID_PS                           1004
#define IDC_S2VDDP_B                    1004
#define ID_PROCESS                      1004
#define ID_AI_DEVICE                    1005
#define ID_SF                           1005
#define IDC_S2VDDP_M                    1005
#define ID_AI_CHANNEL                   1006
#define IDC_S2VEXP_B                    1006
#define ID_AO_CHANNEL                   1007
#define ID_CALC_SF                      1007
#define IDC_S2VEXP_M                    1007
#define IDC_TESTSUMMARY                 1008
#define ID_SCALE                        1008
#define IDC_S3VDDP_B                    1008
#define IDC_LIST_SAMPLES                1008
#define IDC_COMMENTS                    1009
#define IDC_S3VDDP_M                    1009
#define IDC_BUILDTEST                   1010
#define IDC_DATEANDTIME                 1010
#define IDC_S3VEXP_B                    1010
#define IDC_RUNTEST                     1011
#define IDC_SAMPLENUMBER                1011
#define IDC_S3VEXP_M                    1011
#define IDC_TOTAL                       1011
#define IDC_LIGHTCALIBRATION            1012
#define IDC_STARTHOLE                   1012
#define IDC_S4VDDP_B                    1012
#define IDC_LIST_CYCLES                 1012
#define IDC_PROBECALIBRATION            1013
#define IDC_ENDHOLE                     1013
#define IDC_S4VDDP_M                    1013
#define IDC_PROCESSDATA                 1014
#define IDC_SAMPLEID                    1014
#define IDC_S4VEXP_B                    1014
#define IDC_LIST_CYCLESNOT              1014
#define IDC_BUILD_PIDC_TEST             1014
#define IDC_JAZSAVE                     1014
#define IDC_MOTORSPEED                  1015
#define IDC_S4VEXP_M                    1015
#define IDC_ADDCYCLE                    1015
#define IDC_EXIT                        1016
#define IDC_S5VDDP_B                    1016
#define IDC_REMOVECYCLE                 1016
#define IDC_MOTORSPEEDRPM               1016
#define IDC_S5VDDP_M                    1017
#define IDC_REMOVEPOINT                 1017
#define IDC_S5VEXP_B                    1018
#define IDC_ADDPOINT                    1018
#define IDC_FORWARD                     1019
#define IDC_S5VEXP_M                    1019
#define IDC_LIST_POINTS                 1019
#define IDC_BACKWARD                    1020
#define IDC_STATION                     1020
#define IDC_S6VDDP_B                    1020
#define IDC_LIST_POINTSNOT              1020
#define IDC_LOAD                        1021
#define IDC_CHARGINGDEVICE              1021
#define IDC_SAMPLE                      1021
#define IDC_S6VDDP_M                    1021
#define IDC_LIST_AVERAGES               1021
#define IDC_VDDPPROBE                   1022
#define IDC_CYCLES                      1022
#define IDC_S6VEXP_B                    1022
#define IDC_EXPOSEDEVICE                1023
#define IDC_S1_GRID                     1023
#define IDC_S6VEXP_M                    1023
#define IDC_ADDAVERAGE                  1023
#define IDC_VEXPPROBE                   1024
#define IDC_S2_GRID                     1024
#define IDC_AUTO1A                      1024
#define IDC_REMOVEAVERAGE               1024
#define IDC_CHECK_S1_ERASE              1024
#define IDC_TESTSEQUENCEBACKWARD        1025
#define IDC_AUTO1B                      1025
#define IDC_LIST_OUTPOINTS              1025
#define IDC_CHECK_S2_ERASE              1025
#define IDC_TESTSEQUENCELOAD            1026
#define IDC_AUTO2A                      1026
#define IDC_LIST_INPOINTS               1026
#define IDC_CHECK_S3_ERASE              1026
#define IDC_ERASEDEVICE                 1027
#define IDC_S3_GRID                     1027
#define IDC_AUTO2B                      1027
#define IDC_AVGNAME                     1027
#define IDC_CHECK_S4_ERASE              1027
#define IDC_S4_GRID                     1028
#define IDC_DEVICELOAD                  1028
#define IDC_AUTO3A                      1028
#define IDC_COUNT                       1028
#define IDC_CHECK_S5_ERASE              1028
#define IDC_S5_GRID                     1029
#define IDC_DEVICEBACKWARD              1029
#define IDC_AUTO3B                      1029
#define IDC_LIST_SAMPPOS                1029
#define IDC_CHECK_S6_ERASE              1029
#define IDC_S6_GRID                     1030
#define IDC_DEVICEFORWARD               1030
#define IDC_AUTO4A                      1030
#define IDC_HOLES                       1031
#define IDC_TESTSEQUENCEFORWARD         1031
#define IDC_AUTO4B                      1031
#define IDC_S1_PIN                      1032
#define IDC_PROJECTNAME                 1032
#define IDC_AUTO5A                      1032
#define IDC_S2_PIN                      1033
#define IDC_AUTO5B                      1033
#define IDC_PROJECTCOUNTER              1033
#define IDC_S3_PIN                      1034
#define IDC_AUTO6A                      1034
#define IDC_S4_PIN                      1035
#define IDC_AUTO6B                      1035
#define IDC_EDIT1                       1035
#define IDC_TIMELEFT                    1035
#define IDC_PIDC_CYCLES                 1035
#define IDC_VELOCITY_OF_BELT            1035
#define IDC_JAZDIRECTORY                1035
#define IDC_CYCLESBEFOREINCREMENT       1035
#define IDC_CHARGEWINDOW1               1035
#define IDC_S5_PIN                      1036
#define ID_SAVE                         1036
#define IDC_CANCELRECORDINGDATA         1036
#define IDC_JAZPROJECTNAME              1036
#define IDC_CHARGEPINWINDOW1            1036
#define IDC_S6_PIN                      1037
#define ID_EXIT                         1037
#define IDC_CYCLESLEFT                  1037
#define IDC_S1_EXPOSE                   1038
#define IDC_LASTPROBE                   1038
#define IDC_S2_EXPOSE                   1039
#define IDC_LASTZERO                    1039
#define IDC_S3_EXPOSE                   1040
#define IDC_LASTTHOUSAND                1040
#define IDC_S4_EXPOSE                   1041
#define IDC_S5_EXPOSE                   1042
#define IDC_S6_EXPOSE                   1043
#define IDC_S1_ERASE                    1044
#define IDC_S2_ERASE                    1045
#define IDC_S3_ERASE                    1046
#define IDC_S4_ERASE                    1047
#define IDC_S5_ERASE                    1048
#define IDC_S6_ERASE                    1049
#define IDC_RESETCURRENTSEQUENCE        1050
#define IDC_SEQUENCELIST                1051
#define IDC_ADDSEQUENCE                 1052
#define IDC_REMOVESEQUENCE              1053
#define IDC_PROGRESSOFCYCLES            1053
#define IDC_BROWSE                      1054
#define IDC_SETINCREMENTS               1054
#define IDC_MODIFYSEQUENCE              1055
#define IDC_CREATETABLES                1056
#define IDC_REPEATSEQUENCE              1056
#define IDC_PROGRESSOFTABLECREATION     1057
#define IDC_S6_GRID2                    1057
#define IDC_CONVERTTORPM                1058
#define IDC_S6_PIN2                     1058
#define IDC_S6_EXPOSE2                  1059
#define IDC_COPYVALUES                  1060
#define IDC_PASTEVALUES                 1061
#define IDC_S6_ERASE2                   1062
#define IDC_S5_GRID2                    1063
#define IDC_S5_PIN2                     1064
#define IDC_S5_EXPOSE2                  1065
#define IDC_S5_ERASE2                   1066
#define IDC_S4_GRID2                    1067
#define IDC_S4_PIN2                     1068
#define IDC_S4_EXPOSE2                  1069
#define IDC_S4_ERASE2                   1070
#define IDC_S3_GRID2                    1071
#define IDC_S3_PIN2                     1072
#define IDC_S3_EXPOSE2                  1073
#define IDC_PIDC_GRID                   1074
#define IDC_S3_ERASE2                   1074
#define IDC_PIDC_PIN                    1075
#define IDC_S2_GRID2                    1075
#define IDC_S2_PIN2                     1076
#define IDC_S2_EXPOSE2                  1077
#define IDC_PIDC_ERASE                  1078
#define IDC_S2_ERASE2                   1078
#define IDC_S1_GRID2                    1079
#define IDC_S1_PIN2                     1080
#define IDC_S1_EXPOSE2                  1081
#define IDC_S1_ERASE2                   1082
#define IDC_LOAD_PIDC                   1090
#define ID_DETECTOR_SLIT_WIDTH          1091
#define ID_PICOAMMETER_ANALOG_OUTPUT    1092
#define ID_PICOAMMETER_SETTING          1093
#define ID_SCALE_FACTOR                 1094
#define ID_DETECTOR_CALIBRATION_VALUE   1095
#define ID_CALCULATE_SCALE_FACTOR       1096
#define IDC_PIDC_CHECK1                 1097
#define IDC_PIDC_CHECK2                 1098
#define IDC_PIDC_CHECK3                 1099
#define IDC_PIDC_CHECK4                 1100
#define IDC_PIDC_CHECK5                 1101
#define IDC_PIDC_CHECK6                 1102
#define IDC_CYCLES_PIDC                 1103
#define IDC_SETTINGS                    1104
#define IDC_HOLECOUNTER                 1105
#define IDC_ZEROPOSITONCOUNTER          1106
#define IDC_CHARGING_GRID1              1115
#define IDC_CHARGING_GRIDDOWN1          1115
#define IDC_CHARGING_GRID2              1116
#define IDC_CHARGING_GRIDDOWN2          1116
#define IDC_CHARGING_GRID3              1117
#define IDC_CHARGING_GRIDDOWN3          1117
#define IDC_CHARGING_GRID4              1118
#define IDC_CHARGING_GRIDDOWN4          1118
#define IDC_CHARGING_GRID5              1119
#define IDC_CHARGING_GRIDDOWN5          1119
#define IDC_CHARGING_GRID6              1120
#define IDC_CHARGING_GRIDDOWN6          1120
#define IDC_CHARGING_PIN1               1121
#define IDC_CHARGING_GRIDUP1            1121
#define IDC_CHARGING_PIN2               1122
#define IDC_CHARGING_GRIDUP2            1122
#define IDC_CHARGING_PIN3               1123
#define IDC_CHARGING_GRIDUP3            1123
#define IDC_CHARGING_PIN4               1124
#define IDC_CHARGING_GRIDUP4            1124
#define IDC_CHARGING_PIN5               1125
#define IDC_CHARGING_GRIDUP5            1125
#define IDC_CHARGING_PIN6               1126
#define IDC_CHARGING_GRIDUP6            1126
#define IDC_EXPOSEWINDOW1               1128
#define IDC_ERASEWINDOW1                1129
#define IDC_CHARGEWINDOW2               1130
#define IDC_EXPOSEWINDOW2               1131
#define IDC_ERASEWINDOW2                1132
#define IDC_CHARGEWINDOW3               1133
#define IDC_EXPOSEWINDOW3               1134
#define IDC_ERASEWINDOW3                1135
#define IDC_CHARGEWINDOW4               1136
#define IDC_EXPOSEWINDOW4               1137
#define IDC_ERASEWINDOW4                1138
#define IDC_CHARGEWINDOW5               1139
#define IDC_EXPOSEWINDOW5               1140
#define IDC_ERASEWINDOW5                1141
#define IDC_CHARGEWINDOW6               1142
#define IDC_EXPOSEWINDOW6               1143
#define IDC_ERASEWINDOW6                1144
#define IDC_CHARGEPINWINDOW2            1145
#define IDC_CHARGEPINWINDOW3            1146
#define IDC_CHARGEPINWINDOW4            1147
#define IDC_BUFFEREDMODE                1148
#define IDC_NONBUFFEREDMODE             1149
#define IDC_NONBUFFEREDDYNAMICMODE      1150
#define IDC_CHARGEPINWINDOW5            1151
#define IDC_TOTALNUMBER                 1151
#define IDC_CHARGEPINWINDOW6            1152
#define IDC_LOWERLIMIT                  1152
#define IDC_UPPERLIMIT                  1153
#define IDC_CANCELINCREMENTENTER        1154
#define IDC_S1_PIN_LIST                 1156
#define IDC_GRID1_LIST                  1157
#define IDC_GRID2_LIST                  1158
#define IDC_GRID6_LIST                  1159
#define IDC_POPUPCHECK                  1160
#define IDC_EDIT2                       1161
#define IDC_GRID5_LIST                  1162
#define IDC_EDIT3                       1162
#define IDC_GRID3_LIST                  1163
#define IDC_EDIT4                       1163
#define IDC_GRID4_LIST                  1164
#define IDC_SECTIONBCYCLES              1165
#define IDC_SECTIONACYCLES              1166

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1167
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
